import React from 'react';

const Header = () => {
  return (
    <header className="border-b-4 border-white py-8">
      <div className="container mx-auto max-w-6xl px-4">
        <h1 className="text-4xl retro-text text-center text-white mb-4">
          AI GAME ARCADE
        </h1>
        <p className="text-center text-gray-400 retro-text text-sm">
          SINGLE-FILE GAMES GENERATED BY AI
        </p>
      </div>
    </header>
  );
};

export default Header;